config/routes.rb
Rails.application.routes.draw do
  resources :song_involvements

  resources :songs

  resources :artists

  root 'artists#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base

	has_many :song_involvements
	has_many :songs, through: :song_involvements
	

	def self.search(search)
	  if search
	    where('name ILIKE ?', "%#{search}%")
	  else
	    where(nil)
	  end
	end

	def self.artistCollabs(artist)
		if artist
			searchedArtist = where('LOWER(name) = ?', "#{artist.downcase}").first
			puts 'searched artist is'
			if !searchedArtist
        return ['not a valid artist name']
      end
			puts searchedArtist
			# return all collaborations, and filter out the searched-for artist
			collabsArray = searchedArtist.songs.map{|i| i.artists}.flatten.map{|c| c.name}.select{|u| u.downcase != artist.downcase}
			# puts 'collabs-Array is: '
			# puts collabsArray
		end
	end

	scope :artist_producers, -> {includes(:song_involvements).where( :song_involvements => { :producer => true } )}


end

app/models/song.rb
class Song < ActiveRecord::Base

	has_many :song_involvements
	has_many :artists, through: :song_involvements

end

app/models/song_involvement.rb
class SongInvolvement < ActiveRecord::Base

	belongs_to :song
	belongs_to :artist

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    puts 'search param is:'
    puts params[:search]
    @artists = Artist.artistCollabs(params[:search])
    puts @artists
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist_song_involvements = @artist.song_involvements.includes(song: [:song_involvements])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/song_involvements_controller.rb
class SongInvolvementsController < ApplicationController
  before_action :set_song_involvement, only: [:show, :edit, :update, :destroy]

  # GET /song_involvements
  # GET /song_involvements.json
  def index
    @song_involvements = SongInvolvement.all
  end

  # GET /song_involvements/1
  # GET /song_involvements/1.json
  def show
  end

  # GET /song_involvements/new
  def new
    @song_involvement = SongInvolvement.new
  end

  # GET /song_involvements/1/edit
  def edit
  end

  # POST /song_involvements
  # POST /song_involvements.json
  def create
    @song_involvement = SongInvolvement.new(song_involvement_params)

    respond_to do |format|
      if @song_involvement.save
        format.html { redirect_to @song_involvement, notice: 'Song involvement was successfully created.' }
        format.json { render :show, status: :created, location: @song_involvement }
      else
        format.html { render :new }
        format.json { render json: @song_involvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /song_involvements/1
  # PATCH/PUT /song_involvements/1.json
  def update
    respond_to do |format|
      if @song_involvement.update(song_involvement_params)
        format.html { redirect_to @song_involvement, notice: 'Song involvement was successfully updated.' }
        format.json { render :show, status: :ok, location: @song_involvement }
      else
        format.html { render :edit }
        format.json { render json: @song_involvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_involvements/1
  # DELETE /song_involvements/1.json
  def destroy
    @song_involvement.destroy
    respond_to do |format|
      format.html { redirect_to song_involvements_url, notice: 'Song involvement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song_involvement
      @song_involvement = SongInvolvement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_involvement_params
      params.require(:song_involvement).permit(:song_id, :artist_id, :primary, :featured, :producer)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :song_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/song_involvements_helper.rb
module SongInvolvementsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_artist.html.erb
<div class="artistName"><%= link_to artist.name, artist %></div>

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<div class="headSection">
  <div class="titlesContain">

    <h3>Search for an artist</h3>
  </div>
  <div class="searchContain">
    <%= form_tag artists_path, :method => 'get', :id => "artists_search", :remote => true do %>
      <p>
        <%= text_field_tag :search, params[:search] , placeholder: "Search" %>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
    <div class="validArtist">Not a valid artist name.</div>
  </div>
</div>



<style>

body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  width: 1760px;
  height: 1500px;
  position: relative;
}
svg{
    width: 100%;
    height: 100%;
    margin-top: 105px;
}
path.slice{
    stroke-width:2px;
}

polyline{
    opacity: .3;
    stroke: white;
    stroke-width: 2px;
    fill: none;
}

</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
<script>

var svg = d3.select("body")
    .append("svg")
    .append("g");

svg.append("g")
    .attr("class", "slices");
svg.append("g")
    .attr("class", "labels");
svg.append("g")
    .attr("class", "lines");
svg.append("text")
    .attr("class", "artistNameDisplay");

var width = 960,
    height = 450,
    radius = Math.min(width, height) / 1.65;

var pie = d3.layout.pie()
    .sort(null)
    .value(function(d) {
        return d.value;
    });

var arc = d3.svg.arc()
    .outerRadius(radius * 0.8)
    .innerRadius(radius * 0.4);

var outerArc = d3.svg.arc()
    .innerRadius(radius * 0.9)
    // outerRadius is the radius of the invisible circle 
    // where the polylines change directions to point to names
    .outerRadius(radius * 0.9);

svg.attr("transform", "translate(" + width / 1.65 + "," + height / 1.65 + ")");

var key = function(d){ return d.data.label; };

var color = d3.scale.category20()
    .domain(["Lorem ipsum", "dolor sit", "amet", "consectetur", "adipisicing", "elit", "sed", "do", "eiusmod", "tempor", "incididunt"]);
    //.range(["#98abc5", "#8a89a6", "#7b6888", "#6b486b", "#a05d56", "#d0743c", "#ff8c00"]);

// // initial data set
// function first (){
//     return [
//     { label: "Lorem ipsum",
//       value: 23
//     }, 
//     { label: "dolor sit",
//       value: 2
//     }, 
//     { label: "amet",
//       value: 4
//     }, 
//     { label: "consectetur",
//       value: 7
//     }, 
//     { label: "adipisicing",
//       value: 24
//     }, 
//     { label: "elit",
//       value: 10
//     }, 
//     { label: "sed",
//       value: 7
//     }, 
//     { label: "do",
//       value: 18
//     }, 
//     { label: "eiusmod",
//       value: 6
//     }, 
//     { label: "tempor",
//       value: 7
//     }, 
//     { label: "incididunt",
//       value: 9
//     }
//   ].sort(function(a,b) {
//         return d3.ascending(a.label, b.label);
//     });
// }
// updated data set (retrieved with ajax)
// function second (){
//     return [{ label: "Lorem ipsum",  value: Math.random()}, { label: "dolor sit",  value: Math.random()}, { label: "amet",  value: Math.random()}, { label: "consectetur",  value: Math.random()}, { label: "adipisicing",  value: Math.random()}
//   ].sort(function(a,b) {
//         return d3.ascending(a.label, b.label);
//     });
// }

// change(first());

// instead of calling 'change' on click,
// call it on success of ajax 'get' func., passing in result
// d3.select(".randomize")
//     .on("click", function(){
//         change(second());
//     });

function mergeWithFirstEqualZero(first, second){
    var secondSet = d3.set(); second.forEach(function(d) { secondSet.add(d.label); });

    var onlyFirst = first
        .filter(function(d){ return !secondSet.has(d.label); })
        .map(function(d) { return {label: d.label, value: 0, showing: 0}; });
    return d3.merge([ second, onlyFirst ])
        .sort(function(a,b) {
            return d3.ascending(a.label, b.label);
        });
}

function change(data) {
    var duration = 2500;
    var data0 = svg.select(".slices").selectAll("path.slice")
        .data().map(function(d) { return d.data; });
    if (data0.length == 0) data0 = data;
    var was = mergeWithFirstEqualZero(data, data0);
    var is = mergeWithFirstEqualZero(data0, data);

    /* ------- SLICE ARCS -------*/

    var slice = svg.select(".slices").selectAll("path.slice")
        .data(pie(was), key);

    slice.enter()
        .insert("path")
        .attr("class", "slice")
        .style("fill", function(d) { return color(d.data.label); })
        .each(function(d) {
            this._current = d;
        });

    slice = svg.select(".slices").selectAll("path.slice")
        .data(pie(is), key);

    slice       
        .transition().duration(duration)
        .attrTween("d", function(d) {
            var interpolate = d3.interpolate(this._current, d);
            var _this = this;
            return function(t) {
                _this._current = interpolate(t);
                return arc(_this._current);
            };
        });

    slice = svg.select(".slices").selectAll("path.slice")
        .data(pie(data), key);

    slice
        .exit().transition().delay(duration).duration(0)
        .remove();

    /* ------- TEXT LABELS -------*/

    var text = svg.select(".labels").selectAll("text")
        .data(pie(was), key);

    text.enter()
        .append("text")
        .attr("dy", ".35em")
        .style("opacity", 0)
        .text(function(d) {
            return d.data.label +" "+ d.data.value;
        })
        .each(function(d) {
            this._current = d;
        });
    
    function midAngle(d){
        return d.startAngle + (d.endAngle - d.startAngle)/2;
    }

    text = svg.select(".labels").selectAll("text")
        .data(pie(is), key);

    text.transition().duration(duration)
        .style("opacity", function(d) {
            return d.data.showing == 0 ? 0 : 1;
        })
        .attrTween("transform", function(d) {
            var interpolate = d3.interpolate(this._current, d);
            var _this = this;
            return function(t) {
                var d2 = interpolate(t);
                _this._current = d2;
                var pos = outerArc.centroid(d2);
                pos[0] = radius * (midAngle(d2) < Math.PI ? 1 : -1);
                return "translate("+ pos +")";
            };
        })
        .styleTween("text-anchor", function(d){
            var interpolate = d3.interpolate(this._current, d);
            return function(t) {
                var d2 = interpolate(t);
                return midAngle(d2) < Math.PI ? "start":"end";
            };
        });
    
    text = svg.select(".labels").selectAll("text")
        .data(pie(data), key);

    text
        .exit().transition().delay(duration)
        .remove();

    // update displayed number of collabs 
    text.text(function(d) {
            return d.data.label +" "+ d.data.value;
        });

    /* ------- SLICE TO TEXT POLYLINES -------*/

    var polyline = svg.select(".lines").selectAll("polyline")
        .data(pie(was), key);
    
    polyline.enter()
        .append("polyline")
        .style("opacity", 0)
        .each(function(d) {
            this._current = d;
        });

    polyline = svg.select(".lines").selectAll("polyline")
        .data(pie(is), key);
    
    polyline.transition().duration(duration)
        .style("opacity", function(d) {
            return d.data.showing == 0 ? 0 : .5;
        })
        .attrTween("points", function(d){
            this._current = this._current;
            var interpolate = d3.interpolate(this._current, d);
            var _this = this;
            return function(t) {
                var d2 = interpolate(t);
                _this._current = d2;
                var pos = outerArc.centroid(d2);
                pos[0] = radius * 0.95 * (midAngle(d2) < Math.PI ? 1 : -1);
                return [arc.centroid(d2), outerArc.centroid(d2), pos];
            };          
        });
    
    polyline = svg.select(".lines").selectAll("polyline")
        .data(pie(data), key);
    
    polyline
        .exit().transition().delay(duration)
        .remove();


    // setTimeout(function(){ //must check the bounding-box positions only after transitions are done
    // // pasted from stackoverflow
    // // attempting to prevent label-overlap
    // var prev;
    // svg.select(".labels").selectAll("text").each(function(d, i) {
    //   if(i > 0) {
    //     var thisbb = this.getBoundingClientRect(),
    //         prevbb = prev.getBoundingClientRect();
    //         console.log(thisbb);
    //     // move if they overlap
    //     if(!(thisbb.right < prevbb.left || 
    //             thisbb.left > prevbb.right || 
    //             thisbb.bottom < prevbb.top || 
    //             thisbb.top > prevbb.bottom)) {
    //         var ctx = thisbb.left + (thisbb.right - thisbb.left)/2,
    //             cty = thisbb.top + (thisbb.bottom - thisbb.top)/2,
    //             cpx = prevbb.left + (prevbb.right - prevbb.left)/2,
    //             cpy = prevbb.top + (prevbb.bottom - prevbb.top)/2,
    //             off = Math.sqrt(Math.pow(ctx - cpx, 2) + Math.pow(cty - cpy, 2))/2;
    //         d3.select(this).attr("transform",
    //             "translate(" + Math.cos(((d.startAngle + d.endAngle - Math.PI) / 2)) *
    //                                     (radius + off) + "," +
    //                            Math.sin((d.startAngle + d.endAngle - Math.PI) / 2) *
    //                                     (radius + off) + ")");
    //     }
    //   }
    //   prev = this;
    // });

    // }, 4000);
}

</script>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div>
	<h1 class="producerTitle">
	  <strong>Songs Produced by <%= @artist.name %>:</strong>
	</h1>
	<div class="songsContain">
		<% @artist_song_involvements.each do |i| %>
			<% if i.producer==true %>
				<div class="songContain"><%= i.song.title %> - By <% i.song.song_involvements.each do |k|%>
					<% if k.primary==true %>
						<%= k.artist.name %>
					<%end%>
					<%end%>
					<br>
					<% if i.song.song_link%>
						<div class="songLink"><strong><%= link_to "Listen here", i.song.song_link, :target => "_blank" %></strong></div>
					<%end%>
				</div><br>
			<%end%>

		<%end%>
	</div>
</div>

<%= link_to 'Back To Artists', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProducerApp</title>
  <meta name="viewport" content="initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Exo:800,900|Monoton|Lemon' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,900' rel='stylesheet' type='text/css'>
</head>
<body>
<header>
	
</header>
<div class="mainContain">
<%= yield %>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61313371-1', 'www.beatworm.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/song_involvements/_form.html.erb
<%= form_for(@song_involvement) do |f| %>
  <% if @song_involvement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song_involvement.errors.count, "error") %> prohibited this song_involvement from being saved:</h2>

      <ul>
      <% @song_involvement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.number_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.number_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :primary %><br>
    <%= f.check_box :primary %>
  </div>
  <div class="field">
    <%= f.label :featured %><br>
    <%= f.check_box :featured %>
  </div>
  <div class="field">
    <%= f.label :producer %><br>
    <%= f.check_box :producer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_involvements/edit.html.erb
<h1>Editing song_involvement</h1>

<%= render 'form' %>

<%= link_to 'Show', @song_involvement %> |
<%= link_to 'Back', song_involvements_path %>

app/views/song_involvements/index.html.erb
<h1>Listing song_involvements</h1>

<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>Artist</th>
      <th>Primary</th>
      <th>Featured</th>
      <th>Producer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @song_involvements.each do |song_involvement| %>
      <tr>
        <td><%= song_involvement.song_id %></td>
        <td><%= song_involvement.artist_id %></td>
        <td><%= song_involvement.primary %></td>
        <td><%= song_involvement.featured %></td>
        <td><%= song_involvement.producer %></td>
        <td><%= link_to 'Show', song_involvement %></td>
        <td><%= link_to 'Edit', edit_song_involvement_path(song_involvement) %></td>
        <td><%= link_to 'Destroy', song_involvement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song involvement', new_song_involvement_path %>

app/views/song_involvements/new.html.erb
<h1>New song_involvement</h1>

<%= render 'form' %>

<%= link_to 'Back', song_involvements_path %>

app/views/song_involvements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @song_involvement.song_id %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song_involvement.artist_id %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @song_involvement.primary %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @song_involvement.featured %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @song_involvement.producer %>
</p>

<%= link_to 'Edit', edit_song_involvement_path(@song_involvement) %> |
<%= link_to 'Back', song_involvements_path %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :song_link %><br>
    <%= f.text_field :song_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Song link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.song_link %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Song link:</strong>
  <%= @song.song_link %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>